<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<dict>
  <key>fileTypes</key>
  <array> 
    <string>IL</string>
    <string>ST</string>
    <string>LD</string>
    <string>FBD</string>
    <string>SFC</string>
   </array>
  <key>name</key>
  <string>Autoblocks</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.Autoblocks</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\(\*.*?\*\))</string>
          <key>name</key>
          <string>comment.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&apos;.*?&apos;)</string>
          <key>name</key>
          <string>string.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(%(I|Q|M)(X|B|W|D|L|\*)([0-9]*[0-9])(\.([0-9]*[0-9]))*)</string>
          <key>name</key>
          <string>variable.other.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(ADD|SUB|MUL|DIV|MOD|GT|GE|EQ|NE|LE|LT|JMPC|JMP|CALCN|CALC|CAL|RETCN|RETC|RET|ANDN|AND|ORN|XORN|STN|CAL|LDN|LD|STN|ST|S|R|NOT|MOD|AND|XOR|OR|SQRT)\b)</string>
          <key>name</key>
          <string>keyword.operator.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(((t|T|time|TIME)#([0-9][0-9])(:([0-9][0-9]))+)|((t|T|time|TIME)#-?([0-9]*[0-9]+d)?(_?[0-9]*[0-9]+h)?(_?([0-9]*[0-9]+m)(?!s))?(_?[0-9]*[0-9]+s)?(_?[0-9]*[0-9]+ms)?))</string>
          <key>name</key>
          <string>constant.numeric.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((dt|DT|date_and_time|DATE_AND_TIME)#[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-[0-9][0-9]:[0-9][0-9](:([0-9][0-9]))?(.([0-9][0-9]))?)</string>
          <key>name</key>
          <string>constant.numeric.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((t|T|time|TIME)#[0-9][0-9]:[0-9][0-9](:([0-9][0-9]))?(.([0-9][0-9]))?)</string>
          <key>name</key>
          <string>constant.numeric.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((16|8|2)#[0-9A-F]+)</string>
          <key>name</key>
          <string>constant.numeric.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([-]?[0-9]*\.?[0-9]+(E-?[0-9]+)?)</string>
          <key>name</key>
          <string>constant.numeric.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(TRUE|FALSE)</string>
          <key>name</key>
          <string>constant.language.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(:=&gt;|:=|&lt;=|&gt;=|\.\.|:|\(|\)|\*\*|\*|\/|\+|-|&lt;|&gt;|=|&lt;&gt;|&amp;|,|\[|\]|#|%)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#struct</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(EXPONENT|CARDINAL|INTEGER|RETAIN|NON_RETAIN|CONSTANT|R_EDGE|F_EDGE|VAR_INPUT|VAR_OUTPUT|VAR_IN_OUT|VAR_EXTERNAL|VAR_GLOBAL|VAR_ACCESS|VAR_TEMP|VAR_CONFIG|END_CONFIGURATION|CONFIGURATION|END_RESOURCE|RESOURCE|END_VAR|VAR|END_PROGRAM|END_FUNCTION_BLOCK|END_FUNCTION|FUNCTION_BLOCK|FUNCTION|PROGRAM|END_TYPE|TYPE|ARRAY|AT|WITH|TASK|ON)\b)</string>
          <key>name</key>
          <string>keyword.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(USINT|UDINT|ULINT|UINT|LINT|DINT|SINT|INT|LREAL|REAL|TIME_OF_DAY|DATE_AND_TIME|TIME|DATE|WSTRING|STRING|LWORD|DWORD|WORD|BOOL|BYTE|TON|TOFF|TOD|DT|BINARY|HEX)\b)</string>
          <key>name</key>
          <string>storage.type.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(READ_ONLY|READ_WRITE)</string>
          <key>name</key>
          <string>storage.modifier.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(RETURN|IF|THEN|ELSIF|ELSE|END_IF|CASE|OF|END_CASE|FOR|TO|BY|DO|WHILE|END_WHILE|REPEAT|UNTIL|END_REPEAT|EXIT)\b)</string>
          <key>name</key>
          <string>keyword.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(END_TRANSITION|TRANSITION|END_ACTION|ACTION|END_STEP|STEP|FROM|TO)\b)</string>
          <key>name</key>
          <string>keyword.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(_[A-Za-z][A-Za-z0-9]*)|([A-Za-z][A-Za-z0-9_]*)\b)</string>
          <key>name</key>
          <string>variable.other.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>()</string>
          <key>name</key>
          <string>variable.other.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Autoblocks</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Autoblocks</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Autoblocks</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Autoblocks</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Autoblocks</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.Autoblocks</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.Autoblocks</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#struct</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#struct</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Autoblocks</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.Autoblocks</string>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Autoblocks</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>paramter__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>struct</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\b(STRUCT)\b)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Autoblocks</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#struct__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\b(END_STRUCT)\b)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Autoblocks</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>struct__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\(\*.*?\*\))</string>
          <key>name</key>
          <string>comment.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(USINT|UDINT|ULINT|UINT|LINT|DINT|SINT|INT|LREAL|REAL|TIME_OF_DAY|DATE_AND_TIME|TIME|DATE|WSTRING|STRING|LWORD|DWORD|WORD|BOOL|BYTE|TON|TOFF|TOD|DT|BINARY|HEX)\b)</string>
          <key>name</key>
          <string>storage.type.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(:=&gt;|:=|&lt;=|&gt;=|\.\.|:|\(|\)|\*\*|\*|\/|\+|-|&lt;|&gt;|=|&lt;&gt;|&amp;|,|\[|\]|#|%)</string>
          <key>name</key>
          <string>punctuation.Autoblocks</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(_[A-Za-z][A-Za-z0-9]*)|([A-Za-z][A-Za-z0-9_]*)\b)</string>
          <key>name</key>
          <string>variable.other.Autoblocks</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
